name: Docker Image Retag Action
author: Matt Wise
description: |-
  Pulls a Docker image, tags it, and republishes it back to the registry.
inputs:
  image:
    description: |-
      The fully qualified name of the image you are pulling
      (repository/namespace/image).
    required: true

  source_tag:
    description: The source image tag to pull (ie, `$sha`)
    required: true

  dest_tag:
    description: The destination tag (the new tag) to create and publish
    required: true

  verbose:
    description: |-
      If set to 'true', then the 'set -x' flag will be turned on to help debug
      the action.
    required: false
    default: 'false'

  dry:
    description: |-
      If set to 'true', then the docker image pull will happen and the retag
      will happen - but no image push will happen.
    required: false
    default: 'false'

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_IMAGE: ${{ inputs.image }}
    INPUT_SOURCE_TAG: ${{ inputs.source_tag }}
    INPUT_DEST_TAG: ${{ inputs.dest_tag }}
    INPUT_VERBOSE: ${{ inputs.verbose }}
    INPUT_DRY: ${{ inputs.dry }}
